language: java
jdk:
 - openjdk8
 - openjdk9
addons:
 sonarcloud:
  organization: "silicca"
script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
 - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=silicca